#!/usr/bin/env python3
"""
verify_direct_maynard_IJ_v3.py
==============================

Independent Monte-Carlo cross-check of the ORIGINAL Maynard functionals
I_k(F) and J_1(F) for the single-channel rational product trial

    F(t_1,...,t_k)
      = u * prod_i 1/(c + (k-1)t_i),
      t_i >= 0,  sum_i t_i <= 1.

PURPOSE
-------
This script is deliberately independent of the probabilistic/Fourier
reduction used by certify_v5.py.  In particular it does NOT use

    S_n, p_S, w/m0, characteristic functions, Fourier inversion,
    N, D, or the identity R = k N / D.

Instead it starts directly from Maynard's variational functionals

    I_k(F) =
      int_{Delta_k} F(t)^2 dt,

    J_1(F) =
      int_{Delta_{k-1}}
        [ int_0^{1-sum_{i=2}^k t_i} F(t_1,...,t_k) dt_1 ]^2
      dt_2...dt_k,

and estimates

    R_direct = k * J_1(F) / I_k(F).

For the rational product trial, ONLY the one-dimensional inner t_1 integral
is done analytically:

    int_0^L dt/(c+n t) = log(1+n L/c)/n.

This is not the N/D reduction; it is simply the elementary antiderivative
needed to evaluate the definition of J_1 efficiently.

SAMPLING
--------
Uniform samples on Delta_d = {x_i >= 0, sum x_i <= 1} are generated by
drawing d+1 independent Exp(1) variables and normalising by their sum.
The first d coordinates are uniform on Delta_d.

Since Vol(Delta_d)=1/d!,

    I_k = E_{U(Delta_k)}[F^2] / k!,
    J_1 = E_{U(Delta_{k-1})}[inner^2] / (k-1)!,

hence the volume factors cancel in the Rayleigh quotient as

    R_direct = k^2 * E[J-integrand] / E[I-integrand].

The code works in log space and estimates the ratio with paired-independent
sample streams.  Standard errors are obtained from independent batch
replicates of the FINAL ratio, not from a delta-method approximation.

This is a DIAGNOSTIC / falsification test, not a rigorous certificate.
A PASS means that the direct-IJ Monte Carlo estimate is statistically
compatible with a supplied reference value.  The rigorous proof remains
the Arb certificate + standalone verifier.

Examples
--------
From an exported rational .npz:

    python verify_direct_maynard_IJ.py --npz k4000_single.npz \
        --samples 2000000 --batches 40

At a moderate k with explicit c:

    python verify_direct_maynard_IJ.py --k 20 \
        --c 0.20 --reference 3.1 \
        --samples 2000000 --batches 40

For the intended reviewer check, small k is preferable. Direct uniform
simplex Monte Carlo can become severely variance-dominated as k grows because
the integrands become increasingly concentrated. The script therefore applies
an explicit stability gate and refuses to interpret unstable runs.
"""

from __future__ import annotations

import argparse
import hashlib
import math
import sys
import time
from fractions import Fraction
from pathlib import Path

import numpy as np


def parse_fraction(s: str) -> Fraction:
    return Fraction(s)


def load_npz(path: str):
    try:
        with np.load(path, allow_pickle=False) as archive:
            d = {name: archive[name] for name in archive.files}
    except ValueError as exc:
        raise ValueError(
            f"{path!s} is not a pickle-free NumPy NPZ export; re-export it "
            "with the current ratio discovery") from exc
    required = {"k", "c_num", "c_den", "power", "canonical", "sha256"}
    missing = required.difference(d)
    if missing:
        raise ValueError(f"npz missing required fields: {sorted(missing)}")

    canonical = str(d["canonical"])
    sha = hashlib.sha256(canonical.encode()).hexdigest()
    stored_sha = str(d["sha256"])
    if sha != stored_sha:
        raise ValueError("sha256 mismatch: .npz canonical trial has been altered")

    epsilon = (Fraction(int(d["epsilon_num"]), int(d["epsilon_den"]))
               if "epsilon_num" in d else Fraction(0))
    if epsilon != 0:
        raise ValueError(
            "direct-IJ verification currently supports epsilon=0 only; "
            f"this discovery export has epsilon={epsilon}")

    k = int(d["k"])
    powers = [int(x) for x in d["power"]]
    if len(powers) != 1 or powers[0] != 1:
        raise ValueError("direct-IJ checker currently supports one power-1 channel only")

    nums = list(d["c_num"])
    dens = list(d["c_den"])
    if len(nums) != 1:
        raise ValueError("direct-IJ checker currently supports one channel only")
    c = Fraction(int(nums[0]), int(dens[0]))

    reference = None
    if "R_discovery" in d:
        reference = float(d["R_discovery"])

    return {
        "k": k,
        "c": c,
        "reference": reference,
        "epsilon": epsilon,
        "canonical": canonical,
        "sha256": sha,
    }


def uniform_simplex(rng: np.random.Generator, m: int, d: int) -> np.ndarray:
    """m independent points uniformly distributed on Delta_d."""
    # Exponential normalisation is exactly Dirichlet(1,...,1).
    e = rng.exponential(scale=1.0, size=(m, d + 1))
    e /= e.sum(axis=1, keepdims=True)
    return e[:, :d]


def logmeanexp(x: np.ndarray) -> float:
    """log(mean(exp(x))) stably."""
    if x.size == 0:
        raise ValueError("logmeanexp of empty array")
    xmax = float(np.max(x))
    if not math.isfinite(xmax):
        return xmax
    return xmax + math.log(float(np.mean(np.exp(x - xmax))))


def one_batch(rng_I, rng_J, k: int, c: float, m: int, chunk: int):
    """One independent batch estimate of log E[I-integrand], log E[J-integrand]."""
    n = k - 1

    # Accumulate scaled sums in log-domain chunks, then combine via logaddexp.
    logsum_I = -math.inf
    logsum_J = -math.inf
    done = 0

    while done < m:
        q = min(chunk, m - done)

        # ----- I_k: direct uniform sampling on Delta_k -----
        T = uniform_simplex(rng_I, q, k)
        # log F^2 = -2 sum_i log(c+n t_i); u cancels.
        logFI2 = -2.0 * np.log(c + n * T).sum(axis=1)
        chunk_logsum_I = logmeanexp(logFI2) + math.log(q)
        logsum_I = np.logaddexp(logsum_I, chunk_logsum_I)

        # ----- J_1: direct uniform sampling on Delta_{k-1} -----
        U = uniform_simplex(rng_J, q, k - 1)
        s = U.sum(axis=1)
        L = np.maximum(0.0, 1.0 - s)

        # prod_{i=2}^k g(t_i)^2
        log_prod2 = -2.0 * np.log(c + n * U).sum(axis=1)

        # [int_0^L g(t_1) dt_1]^2
        inner = np.log1p(n * L / c) / n
        # inner can theoretically be zero only on a boundary of measure zero.
        log_inner2 = 2.0 * np.log(np.maximum(inner, np.finfo(float).tiny))

        logJ = log_prod2 + log_inner2
        chunk_logsum_J = logmeanexp(logJ) + math.log(q)
        logsum_J = np.logaddexp(logsum_J, chunk_logsum_J)

        done += q

    logmean_I = logsum_I - math.log(m)
    logmean_J = logsum_J - math.log(m)

    # Vol(Delta_{k-1}) / Vol(Delta_k) = k, and R = k J_1 / I_k.
    logR = 2.0 * math.log(k) + logmean_J - logmean_I
    R = math.exp(logR)
    return R, logmean_I, logmean_J


def run_direct_IJ(k: int, c_frac: Fraction, samples: int, batches: int,
                  chunk: int, seed: int):
    if k < 2:
        raise ValueError("k must be >= 2")
    if c_frac <= 0:
        raise ValueError("c must be positive")
    if samples < batches:
        raise ValueError("samples must be >= batches")
    if batches < 4:
        raise ValueError("use at least 4 batches for a meaningful SE")

    c = float(c_frac)
    per = samples // batches
    actual = per * batches
    if per < 100:
        raise ValueError("too few samples per batch")

    # SeedSequence gives genuinely separate reproducible streams.
    ss = np.random.SeedSequence(seed)
    children = ss.spawn(2 * batches)

    Rs = np.empty(batches, dtype=float)
    logIs = np.empty(batches, dtype=float)
    logJs = np.empty(batches, dtype=float)

    t0 = time.time()
    for b in range(batches):
        rngI = np.random.default_rng(children[2*b])
        rngJ = np.random.default_rng(children[2*b + 1])
        R, lI, lJ = one_batch(rngI, rngJ, k, c, per, chunk)
        Rs[b] = R
        logIs[b] = lI
        logJs[b] = lJ

    # Ratio estimators are mildly biased; batching lets us report empirical
    # variation of the complete estimator and is more transparent here.
    R_mean = float(Rs.mean())
    R_sd = float(Rs.std(ddof=1))
    R_se = R_sd / math.sqrt(batches)

    # Student-t critical ~ normal for >=20 batches. To avoid scipy dependency,
    # use 1.96; this is explicitly diagnostic, not a confidence certificate.
    ci_lo = R_mean - 1.96 * R_se
    ci_hi = R_mean + 1.96 * R_se

    # Also combine all batch means in log space to give pooled I,J estimates.
    # Each batch has equal size.
    logI_pool = float(np.logaddexp.reduce(logIs) - math.log(batches))
    logJ_pool = float(np.logaddexp.reduce(logJs) - math.log(batches))
    R_pool = math.exp(2.0 * math.log(k) + logJ_pool - logI_pool)

    return {
        "samples": actual,
        "batches": batches,
        "samples_per_batch": per,
        "seconds": time.time() - t0,
        "R_batch_mean": R_mean,
        "R_batch_sd": R_sd,
        "R_se": R_se,
        "ci95": (ci_lo, ci_hi),
        "R_pooled": R_pool,
        "log_E_I_integrand": logI_pool,
        "log_E_J_integrand": logJ_pool,
        "batch_R": Rs,
    }


def main():
    ap = argparse.ArgumentParser(
        description="Independent direct Monte-Carlo check of Maynard I_k and J_1"
    )
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--npz", type=str, help="single-channel rational discovery npz")
    src.add_argument("--k", type=int, help="k for explicit --c mode")
    src.add_argument("--kc-list", type=str,
                     help="sweep mode: comma list of k:c[:reference], e.g. "
                          "'5:0.564571882307:1.9966686,12:0.413773607'")

    ap.add_argument("--c", type=str,
                    help="positive c (decimal or num/den); required with --k")
    ap.add_argument("--reference", type=float, default=None,
                    help="reference R to compare against; with --npz defaults to R_discovery")
    ap.add_argument("--samples", type=int, default=1_000_000,
                    help="total Monte Carlo samples PER functional (default 1,000,000)")
    ap.add_argument("--batches", type=int, default=40,
                    help="independent batches for empirical SE (default 40)")
    ap.add_argument("--chunk", type=int, default=5000,
                    help="samples generated at once (default 5000)")
    ap.add_argument("--seed", type=int, default=20260810)
    ap.add_argument("--sigma", type=float, default=4.0,
                    help="compatibility threshold in standard errors (default 4)")
    args = ap.parse_args()

    if args.kc_list:
        # sweep: same estimator, several (k, c) pairs; one summary line each.
        print("DIRECT MAYNARD I_k / J_1 CROSS-CHECK  (sweep mode)")
        print("==================================================")
        any_bad = False
        for item in args.kc_list.split(","):
            parts = item.strip().split(":")
            kk = int(parts[0]); cf = parse_fraction(parts[1])
            ref = float(parts[2]) if len(parts) > 2 else None
            out = run_direct_IJ(k=kk, c_frac=cf, samples=args.samples,
                                batches=args.batches, chunk=args.chunk,
                                seed=args.seed + kk)
            line = (f"  k={kk:5d} c={float(cf):.9f}  "
                    f"R = {out['R_batch_mean']:.7f} +- {out['R_se']:.7f}")
            if ref is not None and out["R_se"] > 0:
                z = (out["R_batch_mean"] - ref) / out["R_se"]
                line += f"   ref {ref:.7f}   z = {z:+.2f} SE"
                if abs(z) > args.sigma:
                    line += "   *** OUTSIDE GATE ***"
                    any_bad = True
            print(line + f"   [{out['seconds']:.0f}s]")
        print()
        print("  PASS" if not any_bad else "  WARNING: at least one sweep point "
              "outside the gate")
        sys.exit(1 if any_bad else 0)

    if args.npz:
        rec = load_npz(args.npz)
        k = rec["k"]
        c_frac = rec["c"]
        reference = args.reference if args.reference is not None else rec["reference"]
        print("DIRECT MAYNARD I_k / J_1 CROSS-CHECK")
        print("====================================")
        print(f"  source         : {args.npz}")
        print(f"  canonical      : {rec['canonical'][:100]}")
        print(f"  sha256         : {rec['sha256'][:16]}... (verified)")
    else:
        if args.c is None:
            ap.error("--c is required when using --k")
        k = args.k
        c_frac = parse_fraction(args.c)
        reference = args.reference
        print("DIRECT MAYNARD I_k / J_1 CROSS-CHECK")
        print("====================================")

    print(f"  k              : {k}")
    print(f"  n              : {k-1}")
    print(f"  c              : {c_frac} = {float(c_frac):.12g}")
    print(f"  samples        : {args.samples:,} per functional")
    print(f"  batches        : {args.batches}")
    print()
    print("  Route used:")
    print("    I_k  = direct uniform-simplex integral in dimension k")
    print("    J_1  = direct uniform-simplex outer integral in dimension k-1")
    print("           with only the elementary t_1 antiderivative evaluated analytically")
    print("    R    = k J_1 / I_k")
    print()
    print("  NOT used: S_n, N/D, Fourier inversion, characteristic functions, Arb.")

    out = run_direct_IJ(
        k=k,
        c_frac=c_frac,
        samples=args.samples,
        batches=args.batches,
        chunk=args.chunk,
        seed=args.seed,
    )

    print()
    print("RESULT")
    print("------")
    print(f"  actual samples : {out['samples']:,} per functional")
    print(f"  runtime        : {out['seconds']:.2f} s")
    print(f"  R pooled       : {out['R_pooled']:.10f}")
    print(f"  R batch mean   : {out['R_batch_mean']:.10f}")
    print(f"  batch SD       : {out['R_batch_sd']:.6g}")
    print(f"  SE(R)          : {out['R_se']:.6g}")
    print(f"  approx 95% CI  : [{out['ci95'][0]:.10f}, {out['ci95'][1]:.10f}]")

    # ------------------------------------------------------------------
    # Stability gate: do not interpret a heavy-tailed / variance-dominated
    # uniform-simplex run as evidence for or against the reduction.
    # ------------------------------------------------------------------
    pooled_gap = abs(out["R_pooled"] - out["R_batch_mean"])
    pooled_gap_se = pooled_gap / out["R_se"] if out["R_se"] > 0 else math.inf
    rel_batch_sd = (
        out["R_batch_sd"] / abs(out["R_batch_mean"])
        if out["R_batch_mean"] != 0 else math.inf
    )

    stable = (
        math.isfinite(out["R_pooled"])
        and math.isfinite(out["R_batch_mean"])
        and math.isfinite(out["R_se"])
        and out["R_batch_mean"] > 0
        and pooled_gap_se <= 2.0
        and rel_batch_sd <= 1.0
    )

    print()
    print("MONTE CARLO STABILITY")
    print("---------------------")
    print(f"  |pooled-batch mean| : {pooled_gap:.6g}")
    print(f"  pooled gap / SE     : {pooled_gap_se:.3f}")
    print(f"  batch SD / mean     : {rel_batch_sd:.3f}")

    if not stable:
        print()
        print("  FAIL DIAGNOSTIC: uniform-simplex Monte Carlo is variance-dominated.")
        print("  No comparison with a reference value is statistically meaningful.")
        print("  Use a smaller k and/or a better importance-sampling proposal.")
    elif reference is not None:
        diff = out["R_batch_mean"] - reference
        z = diff / out["R_se"] if out["R_se"] > 0 else math.inf
        print()
        print("REFERENCE COMPARISON")
        print("--------------------")
        print("  IMPORTANT: the reference must be R for this exact same (k,c) trial,")
        print("             not an optimized M_k value or an unrelated benchmark.")
        print(f"  reference R    : {reference:.10f}")
        print(f"  difference     : {diff:+.6g}")
        print(f"  z-distance     : {z:+.3f} SE")
        passed = abs(z) <= args.sigma
        if passed:
            print(f"  PASS diagnostic: direct I/J estimate is within {args.sigma:g} SE of reference.")
        else:
            print(f"  WARNING: direct I/J estimate differs by more than {args.sigma:g} SE.")
            print("  Increase --samples and inspect batch stability before drawing conclusions.")

    print()
    print("INTERPRETATION")
    print("--------------")
    print("  This is a non-rigorous independent falsification check of the")
    print("  reduction from Maynard's original I_k,J_1 functionals to the")
    print("  later one-dimensional formulation. It does not contribute to")
    print("  the certified lower bound itself.")
    if not stable:
        print("  This run is explicitly marked INVALID for reduction validation.")


if __name__ == "__main__":
    main()
